# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protokube.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protokube.proto',
  package='protokube',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fprotokube.proto\x12\tprotokube\"\x15\n\x06Vessel\x12\x0b\n\x03Val\x18\x01 \x01(\x03\x32O\n\nBiStreamer\x12\x41\n\x13\x42idirectionalStream\x12\x11.protokube.Vessel\x1a\x11.protokube.Vessel\"\x00(\x01\x30\x01\x62\x06proto3')
)




_VESSEL = _descriptor.Descriptor(
  name='Vessel',
  full_name='protokube.Vessel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Val', full_name='protokube.Vessel.Val', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=51,
)

DESCRIPTOR.message_types_by_name['Vessel'] = _VESSEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vessel = _reflection.GeneratedProtocolMessageType('Vessel', (_message.Message,), {
  'DESCRIPTOR' : _VESSEL,
  '__module__' : 'protokube_pb2'
  # @@protoc_insertion_point(class_scope:protokube.Vessel)
  })
_sym_db.RegisterMessage(Vessel)



_BISTREAMER = _descriptor.ServiceDescriptor(
  name='BiStreamer',
  full_name='protokube.BiStreamer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=53,
  serialized_end=132,
  methods=[
  _descriptor.MethodDescriptor(
    name='BidirectionalStream',
    full_name='protokube.BiStreamer.BidirectionalStream',
    index=0,
    containing_service=None,
    input_type=_VESSEL,
    output_type=_VESSEL,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BISTREAMER)

DESCRIPTOR.services_by_name['BiStreamer'] = _BISTREAMER

# @@protoc_insertion_point(module_scope)
