# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protokube_pb2 as protokube__pb2


class BiStreamerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BidirectionalStream = channel.stream_stream(
        '/protokube.BiStreamer/BidirectionalStream',
        request_serializer=protokube__pb2.Vessel.SerializeToString,
        response_deserializer=protokube__pb2.Vessel.FromString,
        )


class BiStreamerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def BidirectionalStream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BiStreamerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BidirectionalStream': grpc.stream_stream_rpc_method_handler(
          servicer.BidirectionalStream,
          request_deserializer=protokube__pb2.Vessel.FromString,
          response_serializer=protokube__pb2.Vessel.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protokube.BiStreamer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
