apiVersion: apps/v1
kind: Deployment                  # Kubernetes controller objects
metadata:
  name: pykube       # Pod name
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: pykube        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: pykube
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: pykube
        image: fliropp/pykube:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 50051
            protocol: TCP # Should match the port number that the Go application listens on
---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: pykube-service   # Name of the resource
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - protocol: TCP
    port: 50051
    targetPort: 50051
  selector:
    app: pykube
  sessionAffinity: None
