# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pykube.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pykube.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cpykube.proto\x12\x04grpc\"\x1a\n\x07PingReq\x12\x0f\n\x07request\x18\x01 \x01(\t\"\x1c\n\x08PingResp\x12\x10\n\x08response\x18\x01 \x01(\t2c\n\x04Ping\x12*\n\x07GetPing\x12\r.grpc.PingReq\x1a\x0e.grpc.PingResp\"\x00\x12/\n\nStreamPing\x12\r.grpc.PingReq\x1a\x0e.grpc.PingResp\"\x00\x30\x01\x62\x06proto3')
)




_PINGREQ = _descriptor.Descriptor(
  name='PingReq',
  full_name='grpc.PingReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='grpc.PingReq.request', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=48,
)


_PINGRESP = _descriptor.Descriptor(
  name='PingResp',
  full_name='grpc.PingResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='grpc.PingResp.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['PingReq'] = _PINGREQ
DESCRIPTOR.message_types_by_name['PingResp'] = _PINGRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingReq = _reflection.GeneratedProtocolMessageType('PingReq', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQ,
  '__module__' : 'pykube_pb2'
  # @@protoc_insertion_point(class_scope:grpc.PingReq)
  })
_sym_db.RegisterMessage(PingReq)

PingResp = _reflection.GeneratedProtocolMessageType('PingResp', (_message.Message,), {
  'DESCRIPTOR' : _PINGRESP,
  '__module__' : 'pykube_pb2'
  # @@protoc_insertion_point(class_scope:grpc.PingResp)
  })
_sym_db.RegisterMessage(PingResp)



_PING = _descriptor.ServiceDescriptor(
  name='Ping',
  full_name='grpc.Ping',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=80,
  serialized_end=179,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPing',
    full_name='grpc.Ping.GetPing',
    index=0,
    containing_service=None,
    input_type=_PINGREQ,
    output_type=_PINGRESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamPing',
    full_name='grpc.Ping.StreamPing',
    index=1,
    containing_service=None,
    input_type=_PINGREQ,
    output_type=_PINGRESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PING)

DESCRIPTOR.services_by_name['Ping'] = _PING

# @@protoc_insertion_point(module_scope)
